name: "Release features"
on:
  workflow_dispatch:
jobs:
  deploy:
    if: "${{ github.ref == 'refs/heads/main' }}"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
      packages: "write"
      pull-requests: "write"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Publish features"
        uses: "devcontainers/action@v1"
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          generate-docs: "true"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Commit documentation"
        uses: "stefanzweifel/git-auto-commit-action@v5"
