name: "Release dev container features"
on:
  workflow_dispatch:
jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
      packages: "write"
      pull-requests: "write"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Publish Features"
        uses: "devcontainers/action@v1"
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          generate-docs: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Document Features"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          git add */**/README.md
          git commit -m "docs: update documentation" || export NO_UPDATES=1
	        if [[ -z "$NO_UPDATES" ]]; then
            git push
          fi
